version: '2'
services:

  redis:
    image: redis:latest
    ports:
      - "6739:6739"

  db:
    image: mysql:5.7
    container_name: laravel_project_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  php:
    image: webdevops/php:7.4
    container_name: laravel_project_php
    command: |
      bash -c "ls -l && ls -l ./app && apt-get update && apt-get install -y procps && supervisord"
    volumes:
      - "./:/app"
    working_dir: '/app'

  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: laravel_project_nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/app"
    ports:
      - "80:80"
